version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/guifgr/dio-expert-session-go
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run tests
          command: go test -v ./...
